name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        strategy:
          matrix:
            node-version: [18, 20]
            operating-system: [ubuntu-latest, macos-latest]
            exclude:
              - node-version: 18
                operating-system: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: Cache Node Modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          if: always()
          id: unit-testing-step
          run: npm test

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with: 
            name: Mocha-Test-Result-${{ matrix.node-version }}-${{ matrix.operating-system }}
            path: test-results.xml

    code-coverage:
      strategy:
        matrix:
          node-version: [18, 19, 20]
          operating-system: [ubuntu-latest, macos-latest]
          exclude:
            - node-version: 18
              operating-system: macos-latest
      name: Code coverage
      runs-on: ${{ matrix.operating-system }}
      steps:

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install Dependencies
          run: npm install

        - name: Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Code Coverage Result 
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result-${{ matrix.node-version }}-${{ matrix.operating-system }}
            path: coverage/coverage-final.json
            retention-days: 5
    docker:
      name: Container Build and Push
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            # path to the Dockerfile
            context: .
            push: false
            tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
        

        - name: Docker Image Test
          run: |
            docker images
            docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      
            echo Testing Image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            # path to the Dockerfile
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
    dev-deployment:
      name: Dev Deployment
      needs: [docker]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install kubectl
          uses: azure/setup-kubectl@v4
          with:
            version: v1.31.0

        - name: Create kubernetes cluster with ingress support
          uses: helm/kind-action@v1
          with:
            cluster_name: ingress-cluster
        - name: Install NGINX Ingress Controller
          run: |
              kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
                        
              # Wait for ingress controller to be ready
              echo "Waiting for ingress controller..."
              kubectl wait --namespace ingress-nginx \
                --for=condition=ready pod \
                --selector=app.kubernetes.io/component=controller \
                --timeout=300s
        - name: Test kubernetes cluster
          run: |
            kubectl version -o yaml
            echo ---------
            kubectl get nodes

        - name: Get ingress ip
          run: |
            INGRESS_IP='localhost'
            echo "INGRESS_IP=$INGRESS_IP">>$GITHUB_ENV
        - name: Replace tokens in manifest file
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["kubernetes/development/*.yaml"]'
          env:
              NAMESPACE: ${{ vars.NAMESPACE }}
              REPLICAS: ${{ vars.REPLICAS }}
              IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
              INGRESS_IP: ${{env.INGRESS_IP}}

        - name: Test token configuration
          run: | 
            cat kubernetes/development/*.yaml
          
        - name: Create development namespace
          run: |
            kubectl create namespace ${{vars.NAMESPACE}}
       
        - name: Create secret 
          run: |
            kubectl -n development create secret generic mongo-db-creds \
              --from-literal=MONGO_URI="${{ env.MONGO_URI }}" \
              --from-literal=MONGO_USERNAME="${{ env.MONGO_USERNAME }}" \
              --from-literal=MONGO_PASSWORD="${{ env.MONGO_PASSWORD }}" \
              --dry-run=client -o yaml | kubectl apply -f -

        - name: Get all resources
          run: |
            kubectl get all -n ${{vars.NAMESPACE}}
        - name: Deploy to dev env
          run: |
            kubectl apply -f kubernetes/development



